apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: sample-ac
webhooks:
- name: sample-ac.default.svc
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    url: "https://sample-ac.local/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDVENDQWZHZ0F3SUJBZ0lVRnBjQUxrSTlCS1hOaTkzM2F2UnpIdVNXNlVjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0pjMkZ0Y0d4bElFTkJNQjRYRFRJek1EVXdPREV5TVRjek1Gb1hEVE16TURVdwpOVEV5TVRjek1Gb3dGREVTTUJBR0ExVUVBd3dKYzJGdGNHeGxJRU5CTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBMzZtWVllZWJ1dUdZYVBBelJqTlFoNHNBclc3aEF3ZmlvL1lwS0RIUzdlT3gKd2R1SXN6RHB4VkdUSXgzeFk5c0RNUHlFTUJlVHBleUpVaFl5ODdiSzlkbUdsRGE5YWhZNFpMNjNtTEowWVdPbgpRMUFoOWs2YnZEbFFxclgwKzYrc1oxNWVCbTk1YTVpZzh1dmJmY1hRa01iUjJhZm1qd25pZWVMVUFUOFdxVnR6CmpKMmFqMHpiTlZ4amRld0RrQzFoOWxpbm1iaFg5dWV2NjFVWHRXVlJJRHA4UGFjTUpiVlcwLzBhK0dwWVJ2OG0KK0RnUDJFVENzNVZYemVHdGw3UVlxU1A4UVFNbkx2Mjl1OUlMb2R3Q2hDQlRpaXVOeHRuWWJuYkhhaDY4MGNldApWSDNhZC80SzBYWHZUSHhpSkJMZDA5V2hHbndzL0k1VithZ1lpS29TendJREFRQUJvMU13VVRBZEJnTlZIUTRFCkZnUVVrMUVCUTJNR0IzMHBvM0UxSk9OcEFJaWxPaEV3SHdZRFZSMGpCQmd3Rm9BVWsxRUJRMk1HQjMwcG8zRTEKSk9OcEFJaWxPaEV3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBd29VdQpBcDJBYjlwSHY0MC9IL1FsRkpFU3JRZjVWUWNRN2tmVm9IQzFqOFdEMVgweDBiL3lCZ1BsQXoxTFNCbFJ6QkJxCjU1U0x5Q0c3K3FTQ25aTksxYzQyNDMyNFVQOHVBRWJCcTVJKzlIQmlBK0RZUWl6WnFicE1WMXN6RVdsaHhsajQKTHU0YlMwMEdSR3g4a05NUDZWekNhOVg2bVBPd2dyVmxaRkRMcDBMdlBKcTZKODVUQVkxenpyMHBwbzZTTTlENAp1WW56U0RYUE1LU2JVWkhUTVhtWEE3elJwWkMzMTNJYWxvMFh0eitEL2NPdzBxWWdzVDBTMEJ3OE9FSXBoWEJZCkRHN3lmdHhZUGdFUHIzZlI5aHFnWDRZK0l4UHlxRXhMNDhhUFhxQnBaSVFyeFYxeVRCcDlpN0FRblBmdU15TmwKbDIrV1luS3ZWSWZHUnNnY0p3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - "v1"
    operations:
    - "CREATE"
    - "UPDATE"
    resources:
    - "pods"

